### ISSUE TITLE
Purchased gems on website, got logged off and no credits.

### ISSUE THREAD

**Issue by c10l** [lane-c-wagner/classroom.qvault.io#3]
I have purchased `500 gems` on https://classroom.qvault.io/ .

The payment went through but I was logged off with some errors displayed on the web page. Upon logging back in, the gems are not credited to my account.

This is the only place I found to get in contact that didn't require opening an account on a social network.

**Comment by lane-c-wagner** [comment]
Hey thanks for reaching out. We'll get this fixed! Are you able to log in
again and refresh your browser?

Let me know if that loads the gems. If not, I'll go in and credit them :)

**Comment by c10l** [comment]
Thanks. That didn't help though.

I received the receipt email after I posted this issue. I will forward it to you.

**Comment by lane-c-wagner** [comment]
No worries. I see the purchase. Sorry for the inconvenience! I've checked to make sure the checkout process still works on my end... Are there any useful screenshots or error messages in the console that would help me troubleshoot the issue?

In the meantime use this coupon code for 2000 free gems: `J5YLJJ` @c10l (it has one use so use it quick ;)

**Comment by lane-c-wagner** [comment]
Got the bug fixed, you should have the original 500 Gems. Feel free to also use the coupon code I emailed you, sorry for the inconvenience.
